import { useMemo, useState } from 'react';
import AccessRequestCard from '../components/AccessRequestCard';
import EvidenceList from '../components/EvidenceList';
import type { Memory } from '../types/api';
type Phase = 'select' | 'result';
export default function DiaryPage({ memories }: { memories: Memory[] }) {
  const dates = [...new Set(memories.map(m => m.event_date).filter(Boolean))] as string[]; const [date, setDate] = useState(dates[0] ?? '2026-09-10'); const candidates = useMemo(() => memories.filter(m => m.event_date === date && m.analysis_allowed), [memories, date]); const [selected, setSelected] = useState<string[]>([]); const [phase, setPhase] = useState<Phase>('select'); const [tab, setTab] = useState<'ai' | 'mine'>('ai'); const [mine, setMine] = useState(''); const [notice, setNotice] = useState('');
  const chosen = candidates.filter(m => selected.includes(m.memory_id)); const reset = (nextDate = date) => { setDate(nextDate); setSelected([]); setPhase('select'); setTab('ai'); setMine(''); setNotice(''); };
  const aiDraft = `今天，我认真看见了自己的感受。${chosen.map(m => m.raw_text).join(' ')} 我不急着给它下结论，只想把这一刻如实留下。`;
  return <div className="page diary-page"><section className="page-intro compact"><div><span className="eyebrow">当日日记</span><h1>把今天，<br/>写成自己的话。</h1><p>先选择当天记录并逐次授权，再把合成草稿改成属于自己的日记。</p></div><div className="demo-note"><span/>合成流程 · 不调用 AI</div></section><div className="diary-layout"><aside className="date-index"><span>选择日期</span>{dates.map(item => <button key={item} className={date === item ? 'active' : ''} onClick={() => reset(item)}><strong>{item.slice(8)}</strong><small>{Number(item.slice(5,7))} 月</small></button>)}</aside>{phase === 'select' ? <AccessRequestCard purpose="diary" candidates={candidates} selected={selected} onToggle={id => setSelected(s => s.includes(id) ? s.filter(x => x !== id) : [...s, id])} onApprove={() => { setPhase('result'); setMine(aiDraft); }}/>: <article className="diary-sheet"><div className="diary-tabs"><button className={tab === 'ai' ? 'active' : ''} onClick={() => setTab('ai')}>AI 原稿</button><button className={tab === 'mine' ? 'active' : ''} onClick={() => setTab('mine')}>我的编辑稿</button><span>合成示例</span></div><header><time>{date.slice(0,4)} 年 {Number(date.slice(5,7))} 月 {Number(date.slice(8))} 日</time><h2>今天，我认真看见了自己的感受</h2></header>{tab === 'ai' ? <p>{aiDraft}</p> : <textarea className="diary-editor" value={mine} onChange={e => setMine(e.target.value)} maxLength={5000}/>}<EvidenceList memories={chosen}/><div className="diary-actions"><button className="ghost-button" onClick={() => reset()}>重新选择记录</button>{tab === 'ai' ? <button className="primary-button" onClick={() => setTab('mine')}>编辑这篇日记</button> : <button className="primary-button" disabled={!mine.trim()} onClick={() => setNotice('编辑稿已在当前演示中保存；刷新后重置。')}>保存编辑稿</button>}</div><p className="form-message">{notice}</p></article>}<aside className="diary-guide"><span className="number-chip">清楚的三步</span><ol><li><i>1</i><span>选择当天记录<small>日期不确定的记录先确认</small></span></li><li><i>2</i><span>一次授权<small>只用于生成这一篇</small></span></li><li><i>3</i><span>核对并编辑<small>原稿、改稿和原文分开</small></span></li></ol><p>真实日记保存与版本历史等待 B 提供接口。</p></aside></div></div>;
}
