import { useEffect, useMemo, useState } from 'react';
import EmotionCard from '../components/EmotionCard';
import type { Memory } from '../types/api';
interface Props { memories: Memory[]; onUpdate: (memory: Memory) => void; onDelete: (id: string) => void; onTogglePermission: (id: string) => void; onStartReflection: (id: string) => void; }
export default function MemoriesPage({ memories, onUpdate, onDelete, onTogglePermission, onStartReflection }: Props) {
  const [emotion, setEmotion] = useState('全部'); const [query, setQuery] = useState(''); const [selected, setSelected] = useState(memories[0]?.memory_id ?? ''); const [editing, setEditing] = useState(false); const [draft, setDraft] = useState<Memory>();
  const emotions = ['全部', ...new Set(memories.flatMap(m => m.emotions))]; const filtered = useMemo(() => memories.filter(m => (emotion === '全部' || m.emotions.includes(emotion)) && (!query || `${m.raw_text}${m.event ?? ''}`.includes(query))), [memories, emotion, query]); const active = memories.find(m => m.memory_id === selected) ?? filtered[0];
  useEffect(() => { if (active) setDraft(active); setEditing(false); }, [active?.memory_id]);
  const save = () => { if (!draft?.raw_text.trim()) return; onUpdate({ ...draft, extraction_status: draft.extraction_status === 'unprocessed' ? 'unprocessed' : 'user_edited', content_version: draft.content_version + 1, updated_at: new Date().toISOString() }); setEditing(false); };
  return <div className="page memories-page"><section className="page-intro compact"><div><span className="eyebrow">情绪记忆</span><h1>那些感受，<br/>都有来处。</h1><p>筛选、核对和修正自己的记录，需要时再把它带进一次回响。</p></div><div className="demo-note"><span/>合成记录 · 刷新后重置</div></section><div className="memory-toolbar"><div className="emotion-filter">{emotions.map(e => <button key={e} className={emotion === e ? 'active' : ''} onClick={() => setEmotion(e)}>{e}</button>)}</div><label className="search-box">⌕<input value={query} onChange={e => setQuery(e.target.value)} placeholder="搜索原文或事件"/></label></div><div className="memory-layout"><section className="memory-stream">{filtered.length ? filtered.map((m, index) => <button className={`memory-row ${active?.memory_id === m.memory_id ? 'active' : ''}`} key={m.memory_id} onClick={() => setSelected(m.memory_id)}><div className="date-rail"><strong>{m.event_date?.slice(5).replace('-', '.') ?? '—'}</strong><span>{m.event_date?.slice(0, 4) ?? '日期未定'}</span><i/></div><div className="memory-copy"><div><h2>{m.event ?? '尚未整理的记录'}</h2><span className={`status-badge ${m.extraction_status}`}>{m.extraction_status === 'user_edited' ? '用户已修改' : m.extraction_status === 'confirmed' ? '用户已确认' : '仅保存'}</span></div><p>{m.raw_text}</p><div className="row-tags">{m.emotions.map(e => <span key={e}>{e}</span>)}<em>{m.analysis_allowed ? '可进入候选' : '仅保存'}</em></div></div><span className="row-index">{String(index + 1).padStart(2, '0')}</span></button>) : <div className="empty-state"><h2>没有找到相符的记录</h2><p>换一个情绪或搜索词看看。</p></div>}</section><aside className="memory-detail">{active && draft ? <><div className="detail-heading"><span>原始内容</span><span>{active.source === 'paste' ? `粘贴${active.source_app ? ` · ${active.source_app}` : ''}` : '手动记录'}</span></div>{editing ? <textarea className="original-editor" value={draft.raw_text} maxLength={2000} onChange={e => setDraft({ ...draft, raw_text: e.target.value })}/> : <p className="original-text">{active.raw_text}</p>}<button className={`permission-switch ${active.analysis_allowed ? 'on' : ''}`} onClick={() => onTogglePermission(active.memory_id)}><i/>{active.analysis_allowed ? '可进入复盘候选' : '仅保存'}</button>{active.extraction_status !== 'unprocessed' && <EmotionCard memory={draft} editable={editing} onChange={setDraft}/>}<div className="detail-actions">{editing ? <><button className="ghost-button" onClick={() => { setDraft(active); setEditing(false); }}>取消</button><button className="primary-button" disabled={!draft.raw_text.trim()} onClick={save}>保存修改</button></> : <><button className="ghost-button" onClick={() => setEditing(true)}>编辑</button><button className="ghost-button danger" onClick={() => { if (window.confirm('删除这条演示记录？刷新页面后样例会恢复。')) onDelete(active.memory_id); }}>删除</button><button className="primary-button" onClick={() => onStartReflection(active.memory_id)}>用它开始回响</button></>}</div></> : <div className="quiet-placeholder"><h2>选择一条记录</h2><p>这里会显示完整原文和你确认过的理解。</p></div>}</aside></div></div>;
}
