import { useEffect, useState } from 'react';
import AccessRequestCard from '../components/AccessRequestCard';
import EvidenceList from '../components/EvidenceList';
import type { Memory } from '../types/api';
export default function ReflectionPage({ memories, initialMemoryId }: { memories: Memory[]; initialMemoryId?: string }) {
  const candidates = memories.filter(m => m.analysis_allowed); const [selected, setSelected] = useState<string[]>(initialMemoryId && candidates.some(m => m.memory_id === initialMemoryId) ? [initialMemoryId] : []); const [question, setQuestion] = useState('遇到类似的紧张时，我曾怎样应对？'); const [result, setResult] = useState(false); const [feedback, setFeedback] = useState('');
  useEffect(() => { if (initialMemoryId && candidates.some(m => m.memory_id === initialMemoryId)) { setSelected([initialMemoryId]); setResult(false); } }, [initialMemoryId]); const chosen = candidates.filter(m => selected.includes(m.memory_id));
  return <div className="page reflection-page"><section className="page-intro compact"><div><span className="eyebrow">跨时间回响</span><h1>回看过去，<br/>也听见现在。</h1><p>带着一个问题回看自己；事实、推测与建议清楚分开。</p></div><div className="demo-note"><span/>合成流程 · 可核对原文</div></section>{!result ? <div className="reflection-start"><section className="reflection-question"><span className="number-chip">先问自己</span><label>这一次想了解什么？<input value={question} maxLength={300} onChange={e => setQuestion(e.target.value)}/></label><p>问题只用于组织这一次回响，不会改变原始记录。</p></section><AccessRequestCard purpose="reflection" candidates={candidates} selected={selected} onToggle={id => setSelected(s => s.includes(id) ? s.filter(x => x !== id) : [...s, id])} onApprove={() => setResult(true)} onDeny={() => setSelected([])}/></div> : <div className="reflection-layout"><aside className="reflection-context"><span className="number-chip">你的问题</span><h2>{question}</h2><p>本次使用 {chosen.length} 条记录。结束后授权不自动延续。</p><button className="ghost-button" onClick={() => { setResult(false); setFeedback(''); }}>重新选择依据</button><EvidenceList memories={chosen}/></aside><section className="reflection-result"><div className="result-heading"><div><span className="number-chip">合成回响示例</span><h2>你曾在表达之后，感到一点松动。</h2></div><button onClick={() => setFeedback('已记录：这段回响不符合你的感受（演示状态）。')}>不符合我的感受</button></div><div className="result-sections"><article><span className="blue-dot"/><h3>记录中的事实</h3><p>你记录过交流前的紧张，也写到表达几句后“轻松了一点”。具体内容可在左侧核对。</p></article><article><span className="apricot-dot"/><h3>可能的观察</h3><p>熟悉的人主动询问，也许曾让表达容易一些。这只是基于当前记录的解释。</p></article><article><span className="green-dot"/><h3>可以考虑的小尝试</h3><p>下一次先允许自己只说一小部分，再记录当时真实的感受。</p></article><article><span className="gray-dot"/><h3>局限</h3><p>记录数量有限，不能判断长期规律，也不代表这种方式总会有效。</p></article></div><p className="form-message">{feedback}</p></section></div>}</div>;
}
